### ISSUE TITLE
ActiveGate log ingest container not starting up.

### ISSUE THREAD

**Issue by prathima18** [dynatrace-oss/fluent-plugin-dynatrace#38]
Activegate Log ingest container creation -  example/activegate.yaml

containers:
      - name: activegate
        image: ${YOUR_ENVIRONMENT_URL}/linux/activegate

Is the above one a valid image after we change the environment_url ?  

below is the mount path that we provide on activegate.yaml

       - name: activegate-configuration
          mountPath: /var/lib/dynatrace/gateway/config_template/custom.properties

**Pod/container creation is erroring out saying  the below error**

MountVolume.SetUp failed for volume "activegate-configuration" : configmap references non-existent config key: custom.properties

**Comment by meibensteiner** [comment]
Yes. When you update the placeholder to your dynatrace environment you should be able to pull the image. If you deployed the secret with your API token beforehand.

Could you share your entire activegate deployment and configmap? This looks like the configmap is simply missing the custom.properties section.

**Comment by meibensteiner** [comment]
I think it was just a case of a missing configmap. Feel free to reopen if the issue persists. :)
