### ISSUE TITLE
Enhance the supportability messaging

### ISSUE THREAD

**Issue by EdwardFROMDynatrace** [dynatrace-oss/fluent-plugin-dynatrace#39]
The project page mentions the following

`This project is developed and maintained by Dynatrace R&D.`

Can the messaging be further enhanced to indicate whether the project is fully supported by Dynatrace or not so its supportability is clear?  Example,

`This project is developed, maintained and supported by Dynatrace R&D.`

Dynatrace customers tends to be uncertain if they'll receive support or not should they come across issues.

**Comment by arminru** [comment]
Hey Edward! I added the statement in the README as requested.
The fact that the integration is supported is also mentioned on https://www.dynatrace.com/hub/detail/fluentd/ by the way.
